import type { Plan, Customer, Complaint, User } from '@/models/types';

// Mock Plans - At least 3 per provider
export const mockPlans: Plan[] = [
  // GTPL Plans (Cable Network)
  {
    id: 1,
    provider: 'GTPL',
    planName: 'GTPL Cable Basic 50 Mbps',
    imageUrl: 'https://via.placeholder.com/400x300?text=GTPL+Cable+Basic',
    price: 499,
    gstRate: 18,
    installationAmount: 500,
    description: 'High-speed cable broadband connection with 50 Mbps download speed. Perfect for small families and home offices.',
  },
  {
    id: 2,
    provider: 'GTPL',
    planName: 'GTPL Cable Premium 100 Mbps',
    imageUrl: 'https://via.placeholder.com/400x300?text=GTPL+Cable+Premium',
    price: 799,
    gstRate: 18,
    installationAmount: 500,
    description: 'Premium cable broadband connection with 100 Mbps download speed. Ideal for streaming and gaming.',
  },
  {
    id: 3,
    provider: 'GTPL',
    planName: 'GTPL Cable Ultra 200 Mbps',
    imageUrl: 'https://via.placeholder.com/400x300?text=GTPL+Cable+Ultra',
    price: 1299,
    gstRate: 18,
    installationAmount: 1000,
    description: 'Ultra-fast cable broadband connection with 200 Mbps download speed. Perfect for heavy users and businesses.',
  },
  // BSNL Plans
  {
    id: 4,
    provider: 'BSNL',
    planName: 'BSNL Fiber Basic',
    imageUrl: 'https://via.placeholder.com/400x300?text=BSNL+Fiber',
    price: 449,
    gstRate: 18,
    installationAmount: 500,
    description: 'Reliable BSNL fiber connection with stable speeds and excellent coverage.',
  },
  {
    id: 5,
    provider: 'BSNL',
    planName: 'BSNL Fiber Plus',
    imageUrl: 'https://via.placeholder.com/400x300?text=BSNL+Plus',
    price: 699,
    gstRate: 18,
    installationAmount: 500,
    description: 'Enhanced BSNL fiber connection with better speeds and reliability.',
  },
  {
    id: 6,
    provider: 'BSNL',
    planName: 'BSNL Fiber Premium',
    imageUrl: 'https://via.placeholder.com/400x300?text=BSNL+Premium',
    price: 999,
    gstRate: 18,
    installationAmount: 1000,
    description: 'Premium BSNL fiber connection with high-speed internet for demanding users.',
  },
  // Railwire Plans
  {
    id: 7,
    provider: 'Railwire',
    planName: 'Railwire Express 75 Mbps',
    imageUrl: 'https://via.placeholder.com/400x300?text=Railwire+Express',
    price: 599,
    gstRate: 18,
    installationAmount: 500,
    description: 'Fast and reliable Railwire connection with 75 Mbps speed.',
  },
  {
    id: 8,
    provider: 'Railwire',
    planName: 'Railwire Speed 150 Mbps',
    imageUrl: 'https://via.placeholder.com/400x300?text=Railwire+Speed',
    price: 899,
    gstRate: 18,
    installationAmount: 500,
    description: 'High-speed Railwire connection with 150 Mbps for power users.',
  },
  {
    id: 9,
    provider: 'Railwire',
    planName: 'Railwire Turbo 300 Mbps',
    imageUrl: 'https://via.placeholder.com/400x300?text=Railwire+Turbo',
    price: 1499,
    gstRate: 18,
    installationAmount: 1000,
    description: 'Turbo-charged Railwire connection with blazing fast 300 Mbps speeds.',
  },
  // Krishiinet Plans
  {
    id: 10,
    provider: 'Krishiinet',
    planName: 'Krishiinet Rural Connect',
    imageUrl: 'https://via.placeholder.com/400x300?text=Krishiinet+Rural',
    price: 399,
    gstRate: 18,
    installationAmount: 500,
    description: 'Affordable internet solution for rural areas with good connectivity.',
  },
  {
    id: 11,
    provider: 'Krishiinet',
    planName: 'Krishiinet Home Plus',
    imageUrl: 'https://via.placeholder.com/400x300?text=Krishiinet+Home',
    price: 549,
    gstRate: 18,
    installationAmount: 500,
    description: 'Enhanced home internet connection with better speeds and coverage.',
  },
  {
    id: 12,
    provider: 'Krishiinet',
    planName: 'Krishiinet Business',
    imageUrl: 'https://via.placeholder.com/400x300?text=Krishiinet+Business',
    price: 799,
    gstRate: 18,
    installationAmount: 1000,
    description: 'Business-grade internet connection with dedicated support and reliability.',
  },
];

// Helper function to generate dates
const getDateString = (daysAgo: number): string => {
  const date = new Date();
  date.setDate(date.getDate() - daysAgo);
  return date.toISOString();
};

// Mock Customers - At least 20 customers with mixed providers, statuses, and dates
export const mockCustomers: Customer[] = [
  {
    id: 1,
    name: 'Rajesh Kumar',
    email: 'rajesh.kumar@example.com',
    mobile: '9876543210',
    password: 'password123',
    connectionType: 'GTPL',
    package: 'GTPL Cable Basic 50 Mbps',
    status: 'Active',
    description: 'Long-term customer, very satisfied with service.',
    address: {
      line1: '123 Main Street',
      line2: 'Near City Park',
      city: 'Mumbai',
      state: 'Maharashtra',
      country: 'India',
    },
    createdAt: getDateString(45),
    paymentStatus: 'paid',
    paymentDescription: 'Monthly bill paid via UPI on 15th.',
    paymentUpdatedAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 2,
    name: 'Priya Sharma',
    email: 'priya.sharma@example.com',
    mobile: '9876543211',
    password: 'password123',
    connectionType: 'BSNL',
    package: 'BSNL Fiber Basic',
    status: 'Active',
    description: 'New customer, installation completed last month.',
    address: {
      line1: '456 Park Avenue',
      line2: 'Block A',
      city: 'Delhi',
      state: 'Delhi',
      country: 'India',
    },
    createdAt: getDateString(25),
  },
  {
    id: 3,
    name: 'Amit Patel',
    email: 'amit.patel@example.com',
    mobile: '9876543212',
    password: 'password123',
    connectionType: 'Railwire',
    package: 'Railwire Express 75 Mbps',
    status: 'Inactive',
    description: 'Service temporarily suspended due to payment issues.',
    address: {
      line1: '789 Tech Road',
      line2: 'Sector 5',
      city: 'Bangalore',
      state: 'Karnataka',
      country: 'India',
    },
    createdAt: getDateString(60),
  },
  {
    id: 4,
    name: 'Sneha Reddy',
    email: 'sneha.reddy@example.com',
    mobile: '9876543213',
    password: 'password123',
    connectionType: 'GTPL',
    package: 'GTPL Cable Premium 100 Mbps',
    status: 'Inactive',
    description: 'Upgraded to premium plan recently.',
    address: {
      line1: '321 Business Park',
      line2: 'Floor 3',
      city: 'Hyderabad',
      state: 'Telangana',
      country: 'India',
    },
    createdAt: getDateString(15),
    paymentStatus: 'not_paid',
    paymentDescription: 'Pending: December bill.',
    paymentUpdatedAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 5,
    name: 'Vikram Singh',
    email: 'vikram.singh@example.com',
    mobile: '9876543214',
    password: 'password123',
    connectionType: 'Krishiinet',
    package: 'Krishiinet Rural Connect',
    status: 'Active',
    description: 'Rural area customer, good connectivity.',
    address: {
      line1: 'Village Road',
      line2: 'Near Post Office',
      city: 'Pune',
      state: 'Maharashtra',
      country: 'India',
    },
    createdAt: getDateString(5),
  },
  {
    id: 6,
    name: 'Anjali Mehta',
    email: 'anjali.mehta@example.com',
    mobile: '9876543215',
    password: 'password123',
    connectionType: 'BSNL',
    package: 'BSNL Fiber Plus',
    status: 'Active',
    description: 'Regular customer, always pays on time.',
    address: {
      line1: '567 Residential Complex',
      line2: 'Tower B',
      city: 'Chennai',
      state: 'Tamil Nadu',
      country: 'India',
    },
    createdAt: getDateString(30),
  },
  {
    id: 7,
    name: 'Rahul Verma',
    email: 'rahul.verma@example.com',
    mobile: '9876543216',
    password: 'password123',
    connectionType: 'Railwire',
    package: 'Railwire Speed 150 Mbps',
    status: 'Active',
    description: 'Business customer, requires high-speed connection.',
    address: {
      line1: '890 Corporate Avenue',
      line2: 'Suite 201',
      city: 'Gurgaon',
      state: 'Haryana',
      country: 'India',
    },
    createdAt: getDateString(8),
  },
  {
    id: 8,
    name: 'Kavita Nair',
    email: 'kavita.nair@example.com',
    mobile: '9876543217',
    password: 'password123',
    connectionType: 'GTPL',
    package: 'GTPL Cable Ultra 200 Mbps',
    status: 'Active',
    description: 'Power user, needs ultra-fast speeds for work.',
    address: {
      line1: '234 Tech Hub',
      line2: 'Unit 15',
      city: 'Noida',
      state: 'Uttar Pradesh',
      country: 'India',
    },
    createdAt: getDateString(12),
    paymentStatus: 'paid',
    paymentDescription: 'Paid in full at office.',
    paymentUpdatedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 9,
    name: 'Mohit Agarwal',
    email: 'mohit.agarwal@example.com',
    mobile: '9876543218',
    password: 'password123',
    connectionType: 'BSNL',
    package: 'BSNL Fiber Premium',
    status: 'Inactive',
    description: 'Service disconnected, customer moved to different city.',
    address: {
      line1: '345 Green Valley',
      line2: 'Apartment 4B',
      city: 'Kolkata',
      state: 'West Bengal',
      country: 'India',
    },
    createdAt: getDateString(90),
  },
  {
    id: 10,
    name: 'Divya Joshi',
    email: 'divya.joshi@example.com',
    mobile: '9876543219',
    password: 'password123',
    connectionType: 'Krishiinet',
    package: 'Krishiinet Home Plus',
    status: 'Active',
    description: 'Home user, satisfied with current plan.',
    address: {
      line1: '678 Suburban Lane',
      line2: 'House No. 12',
      city: 'Ahmedabad',
      state: 'Gujarat',
      country: 'India',
    },
    createdAt: getDateString(20),
  },
  {
    id: 11,
    name: 'Arjun Malhotra',
    email: 'arjun.malhotra@example.com',
    mobile: '9876543220',
    password: 'password123',
    connectionType: 'Railwire',
    package: 'Railwire Turbo 300 Mbps',
    status: 'Active',
    description: 'Gaming enthusiast, requires low latency connection.',
    address: {
      line1: '901 Gaming Street',
      line2: 'Flat 302',
      city: 'Bangalore',
      state: 'Karnataka',
      country: 'India',
    },
    createdAt: getDateString(3),
  },
  {
    id: 12,
    name: 'Pooja Desai',
    email: 'pooja.desai@example.com',
    mobile: '9876543221',
    password: 'password123',
    connectionType: 'GTPL',
    package: 'GTPL Cable Basic 50 Mbps',
    status: 'Active',
    description: 'Budget-conscious customer, happy with basic plan.',
    address: {
      line1: '112 Affordable Housing',
      line2: 'Block C',
      city: 'Surat',
      state: 'Gujarat',
      country: 'India',
    },
    createdAt: getDateString(18),
  },
  {
    id: 13,
    name: 'Suresh Iyer',
    email: 'suresh.iyer@example.com',
    mobile: '9876543222',
    password: 'password123',
    connectionType: 'BSNL',
    package: 'BSNL Fiber Basic',
    status: 'Inactive',
    description: 'Temporary disconnection, will reconnect next month.',
    address: {
      line1: '223 Temple Road',
      line2: 'Near Market',
      city: 'Coimbatore',
      state: 'Tamil Nadu',
      country: 'India',
    },
    createdAt: getDateString(75),
  },
  {
    id: 14,
    name: 'Meera Krishnan',
    email: 'meera.krishnan@example.com',
    mobile: '9876543223',
    password: 'password123',
    connectionType: 'Krishiinet',
    package: 'Krishiinet Business',
    status: 'Active',
    description: 'Small business owner, needs reliable connection for operations.',
    address: {
      line1: '334 Commercial Street',
      line2: 'Shop No. 5',
      city: 'Kochi',
      state: 'Kerala',
      country: 'India',
    },
    createdAt: getDateString(10),
  },
  {
    id: 15,
    name: 'Nikhil Kapoor',
    email: 'nikhil.kapoor@example.com',
    mobile: '9876543224',
    password: 'password123',
    connectionType: 'GTPL',
    package: 'GTPL Cable Premium 100 Mbps',
    status: 'Active',
    description: 'Streaming enthusiast, upgraded for better quality.',
    address: {
      line1: '445 Entertainment Avenue',
      line2: 'Residency 8',
      city: 'Mumbai',
      state: 'Maharashtra',
      country: 'India',
    },
    createdAt: getDateString(7),
  },
  {
    id: 16,
    name: 'Riya Banerjee',
    email: 'riya.banerjee@example.com',
    mobile: '9876543225',
    password: 'password123',
    connectionType: 'Railwire',
    package: 'Railwire Express 75 Mbps',
    status: 'Active',
    description: 'Student, needs internet for online classes.',
    address: {
      line1: '556 College Road',
      line2: 'Hostel Block',
      city: 'Pune',
      state: 'Maharashtra',
      country: 'India',
    },
    createdAt: getDateString(22),
  },
  {
    id: 17,
    name: 'Karan Thakur',
    email: 'karan.thakur@example.com',
    mobile: '9876543226',
    password: 'password123',
    connectionType: 'BSNL',
    package: 'BSNL Fiber Plus',
    status: 'Active',
    description: 'Remote worker, depends on stable connection.',
    address: {
      line1: '667 Work From Home',
      line2: 'Apartment 9A',
      city: 'Jaipur',
      state: 'Rajasthan',
      country: 'India',
    },
    createdAt: getDateString(14),
  },
  {
    id: 18,
    name: 'Shreya Menon',
    email: 'shreya.menon@example.com',
    mobile: '9876543227',
    password: 'password123',
    connectionType: 'Krishiinet',
    package: 'Krishiinet Rural Connect',
    status: 'Inactive',
    description: 'Service suspended due to area maintenance.',
    address: {
      line1: '778 Village Main Road',
      line2: 'House No. 23',
      city: 'Thrissur',
      state: 'Kerala',
      country: 'India',
    },
    createdAt: getDateString(50),
  },
  {
    id: 19,
    name: 'Aditya Rao',
    email: 'aditya.rao@example.com',
    mobile: '9876543228',
    password: 'password123',
    connectionType: 'GTPL',
    package: 'GTPL Cable Ultra 200 Mbps',
    status: 'Active',
    description: 'Tech professional, requires high-speed for development work.',
    address: {
      line1: '889 Developer Hub',
      line2: 'Flat 501',
      city: 'Bangalore',
      state: 'Karnataka',
      country: 'India',
    },
    createdAt: getDateString(2),
  },
  {
    id: 20,
    name: 'Neha Gupta',
    email: 'neha.gupta@example.com',
    mobile: '9876543229',
    password: 'password123',
    connectionType: 'Railwire',
    package: 'Railwire Speed 150 Mbps',
    status: 'Active',
    description: 'Content creator, needs fast upload speeds.',
    address: {
      line1: '990 Content Studio',
      line2: 'Unit 7',
      city: 'Mumbai',
      state: 'Maharashtra',
      country: 'India',
    },
    createdAt: getDateString(1),
  },
  {
    id: 21,
    name: 'Rohit Sharma',
    email: 'rohit.sharma@example.com',
    mobile: '9876543230',
    password: 'password123',
    connectionType: 'BSNL',
    package: 'BSNL Fiber Premium',
    status: 'Active',
    description: 'Family plan, multiple devices connected.',
    address: {
      line1: '101 Family Home',
      line2: 'Ground Floor',
      city: 'Delhi',
      state: 'Delhi',
      country: 'India',
    },
    createdAt: getDateString(6),
  },
  {
    id: 22,
    name: 'Ananya Das',
    email: 'ananya.das@example.com',
    mobile: '9876543231',
    password: 'password123',
    connectionType: 'Krishiinet',
    package: 'Krishiinet Home Plus',
    status: 'Active',
    description: 'New customer, just installed last week.',
    address: {
      line1: '202 New Colony',
      line2: 'House No. 45',
      city: 'Bhubaneswar',
      state: 'Odisha',
      country: 'India',
    },
    createdAt: getDateString(4),
  },
];

// Mock Users (Admin/Employee). Password plain text for mock only. Replace with secure auth & hashing later.
export const mockUsers: User[] = [
  { id: 1, name: 'Admin User', username: 'popna', password: 'test123', role: 'admin', createdAt: getDateString(365) },
  { id: 2, name: 'Employee User', username: 'popna-emp', password: 'test123', role: 'employee', createdAt: getDateString(180) },
];

// Mock Complaints - At least 15 complaints with mixed statuses and providers
export const mockComplaints: Complaint[] = [
  {
    id: 1,
    customerId: 1,
    customerName: 'Rajesh Kumar',
    mobile: '9876543210',
    connectionType: 'GTPL',
    customerDescription: 'Internet speed is very slow during evening hours. Connection drops frequently.',
    internalDescription: 'Checked connection logs. High traffic during peak hours. Investigating bandwidth allocation.',
    status: 'active',
    createdAt: getDateString(2),
  },
  {
    id: 2,
    customerId: 2,
    customerName: 'Priya Sharma',
    mobile: '9876543211',
    connectionType: 'BSNL',
    customerDescription: 'Billing issue - charged extra amount this month. Need clarification on bill.',
    internalDescription: 'Reviewing billing records. May be due to plan upgrade mid-month.',
    status: 'active',
    createdAt: getDateString(1),
  },
  {
    id: 3,
    customerId: 3,
    customerName: 'Amit Patel',
    mobile: '9876543212',
    connectionType: 'Railwire',
    customerDescription: 'Connection not working since yesterday. No internet access at all.',
    internalDescription: 'Urgent - Sending technician today. Suspected fiber cut in area.',
    status: 'active',
    createdAt: getDateString(0),
  },
  {
    id: 4,
    customerId: 4,
    customerName: 'Sneha Reddy',
    mobile: '9876543213',
    connectionType: 'GTPL',
    customerDescription: 'Router needs replacement. Current router keeps restarting.',
    internalDescription: 'Waiting for router stock. Expected delivery in 2 days.',
    status: 'on-hold',
    createdAt: getDateString(5),
  },
  {
    id: 5,
    customerId: 5,
    customerName: 'Vikram Singh',
    mobile: '9876543214',
    connectionType: 'Krishiinet',
    customerDescription: 'Installation pending for 3 days. Need urgent installation.',
    internalDescription: 'Scheduled for tomorrow. Technician assigned.',
    status: 'active',
    createdAt: getDateString(3),
  },
  {
    id: 6,
    customerId: 6,
    customerName: 'Anjali Mehta',
    mobile: '9876543215',
    connectionType: 'BSNL',
    customerDescription: 'Slow download speeds. Not getting promised 100 Mbps.',
    internalDescription: 'Testing connection speed. May need line optimization.',
    status: 'on-hold',
    createdAt: getDateString(7),
  },
  {
    id: 7,
    customerId: 7,
    customerName: 'Rahul Verma',
    mobile: '9876543216',
    connectionType: 'Railwire',
    customerDescription: 'Connection issue resolved. Thank you for quick support.',
    internalDescription: 'Issue resolved by resetting ONT. Customer satisfied.',
    status: 'completed',
    createdAt: getDateString(10),
  },
  {
    id: 8,
    customerId: 8,
    customerName: 'Kavita Nair',
    mobile: '9876543217',
    connectionType: 'GTPL',
    customerDescription: 'Need to upgrade plan. Current plan not sufficient for work from home.',
    internalDescription: 'Contacted customer. Upgrading to 200 Mbps plan.',
    status: 'active',
    createdAt: getDateString(1),
  },
  {
    id: 9,
    customerId: 9,
    customerName: 'Mohit Agarwal',
    mobile: '9876543218',
    connectionType: 'BSNL',
    customerDescription: 'Fiber cable cut due to construction work. Need repair.',
    internalDescription: 'Emergency repair team dispatched. ETA 4 hours.',
    status: 'active',
    createdAt: getDateString(0),
  },
  {
    id: 10,
    customerId: 10,
    customerName: 'Divya Joshi',
    mobile: '9876543219',
    connectionType: 'Krishiinet',
    customerDescription: 'Payment gateway issue. Unable to pay online bill.',
    internalDescription: 'Payment gateway working. Customer can try alternative payment method.',
    status: 'on-hold',
    createdAt: getDateString(4),
  },
  {
    id: 11,
    customerId: 11,
    customerName: 'Arjun Malhotra',
    mobile: '9876543220',
    connectionType: 'Railwire',
    customerDescription: 'High ping in online games. Connection unstable during gaming.',
    internalDescription: 'Checking latency. May need QoS configuration for gaming.',
    status: 'active',
    createdAt: getDateString(2),
  },
  {
    id: 12,
    customerId: 12,
    customerName: 'Pooja Desai',
    mobile: '9876543221',
    connectionType: 'GTPL',
    customerDescription: 'Router configuration issue resolved. Working fine now.',
    internalDescription: 'Fixed router settings. Connection stable now.',
    status: 'completed',
    createdAt: getDateString(8),
  },
  {
    id: 13,
    customerId: 13,
    customerName: 'Suresh Iyer',
    mobile: '9876543222',
    connectionType: 'BSNL',
    customerDescription: 'Service reconnection request. Want to resume connection.',
    internalDescription: 'Processing reconnection. Will activate within 24 hours.',
    status: 'active',
    createdAt: getDateString(1),
  },
  {
    id: 14,
    customerId: 14,
    customerName: 'Meera Krishnan',
    mobile: '9876543223',
    connectionType: 'Krishiinet',
    customerDescription: 'Business connection needs dedicated IP address. Please provide.',
    internalDescription: 'Dedicated IP allocation in progress. Requires network configuration.',
    status: 'on-hold',
    createdAt: getDateString(6),
  },
  {
    id: 15,
    customerId: 15,
    customerName: 'Nikhil Kapoor',
    mobile: '9876543224',
    connectionType: 'GTPL',
    customerDescription: 'Streaming quality poor. Buffering issues on Netflix and YouTube.',
    internalDescription: 'Investigating bandwidth allocation. May need to optimize streaming traffic.',
    status: 'active',
    createdAt: getDateString(0),
  },
  {
    id: 16,
    customerId: 16,
    customerName: 'Riya Banerjee',
    mobile: '9876543225',
    connectionType: 'Railwire',
    customerDescription: 'Connection restored. Issue was from ISP side, now fixed.',
    internalDescription: 'Network maintenance completed. All services restored.',
    status: 'completed',
    createdAt: getDateString(12),
  },
  {
    id: 17,
    customerId: 17,
    customerName: 'Karan Thakur',
    mobile: '9876543226',
    connectionType: 'BSNL',
    customerDescription: 'Need to relocate connection to new address. Please arrange.',
    internalDescription: 'Relocation request received. Survey scheduled for next week.',
    status: 'active',
    createdAt: getDateString(2),
  },
  {
    id: 18,
    customerId: 18,
    customerName: 'Shreya Menon',
    mobile: '9876543227',
    connectionType: 'Krishiinet',
    customerDescription: 'Technical support ticket resolved. Customer satisfied.',
    internalDescription: 'All issues resolved. Customer feedback positive.',
    status: 'completed',
    createdAt: getDateString(15),
  },
];
