// SaaS Ready - Fully Dynamic Product
import type { Plan, Customer, Complaint, User } from '@/models/types';
import { MOCK_ORGANIZATION_ID } from '@/models/types';

// Multi-tenant SaaS Isolation - All mock data scoped by organizationId.
// Products fully dynamic - no hardcoded service names. Mock uses product names from Products API.

// Mock Plans - provider = product name from Admin → Settings → Products
export const mockPlans: Plan[] = [
  {
    id: 1,
    organizationId: MOCK_ORGANIZATION_ID,
    provider: 'Cable',
    planName: 'Cable Basic 50 Mbps',
    imageUrl: 'https://via.placeholder.com/400x300?text=Cable+Basic',
    price: 499,
    gstRate: 18,
    installationAmount: 500,
    description: 'High-speed cable broadband connection with 50 Mbps download speed. Perfect for small families and home offices.',
  },
  {
    id: 2,
    organizationId: MOCK_ORGANIZATION_ID,
    provider: 'Cable',
    planName: 'Cable Premium 100 Mbps',
    imageUrl: 'https://via.placeholder.com/400x300?text=Cable+Premium',
    price: 799,
    gstRate: 18,
    installationAmount: 500,
    description: 'Premium cable broadband connection with 100 Mbps download speed. Ideal for streaming and gaming.',
  },
  {
    id: 3,
    organizationId: MOCK_ORGANIZATION_ID,
    provider: 'Cable',
    planName: 'Cable Ultra 200 Mbps',
    imageUrl: 'https://via.placeholder.com/400x300?text=Cable+Ultra',
    price: 1299,
    gstRate: 18,
    installationAmount: 1000,
    description: 'Ultra-fast cable broadband connection with 200 Mbps download speed. Perfect for heavy users and businesses.',
  },
  // Internet 1
  {
    id: 4,
    organizationId: MOCK_ORGANIZATION_ID,
    provider: 'Internet 1',
    planName: 'Internet 1 Fiber Basic',
    imageUrl: 'https://via.placeholder.com/400x300?text=Internet+1+Fiber',
    price: 449,
    gstRate: 18,
    installationAmount: 500,
    description: 'Reliable fiber connection with stable speeds and excellent coverage.',
  },
  {
    id: 5,
    organizationId: MOCK_ORGANIZATION_ID,
    provider: 'Internet 1',
    planName: 'Internet 1 Fiber Plus',
    imageUrl: 'https://via.placeholder.com/400x300?text=Internet+1+Plus',
    price: 699,
    gstRate: 18,
    installationAmount: 500,
    description: 'Enhanced fiber connection with better speeds and reliability.',
  },
  {
    id: 6,
    organizationId: MOCK_ORGANIZATION_ID,
    provider: 'Internet 1',
    planName: 'Internet 1 Fiber Premium',
    imageUrl: 'https://via.placeholder.com/400x300?text=Internet+1+Premium',
    price: 999,
    gstRate: 18,
    installationAmount: 1000,
    description: 'Premium fiber connection with high-speed internet for demanding users.',
  },
  // Internet 2
  {
    id: 7,
    organizationId: MOCK_ORGANIZATION_ID,
    provider: 'Internet 2',
    planName: 'Internet 2 Express 75 Mbps',
    imageUrl: 'https://via.placeholder.com/400x300?text=Internet+2+Express',
    price: 599,
    gstRate: 18,
    installationAmount: 500,
    description: 'Fast and reliable connection with 75 Mbps speed.',
  },
  {
    id: 8,
    organizationId: MOCK_ORGANIZATION_ID,
    provider: 'Internet 2',
    planName: 'Internet 2 Speed 150 Mbps',
    imageUrl: 'https://via.placeholder.com/400x300?text=Internet+2+Speed',
    price: 899,
    gstRate: 18,
    installationAmount: 500,
    description: 'High-speed connection with 150 Mbps for power users.',
  },
  {
    id: 9,
    organizationId: MOCK_ORGANIZATION_ID,
    provider: 'Internet 2',
    planName: 'Internet 2 Turbo 300 Mbps',
    imageUrl: 'https://via.placeholder.com/400x300?text=Internet+2+Turbo',
    price: 1499,
    gstRate: 18,
    installationAmount: 1000,
    description: 'Turbo-charged connection with blazing fast 300 Mbps speeds.',
  },
  // Internet 3
  {
    id: 10,
    organizationId: MOCK_ORGANIZATION_ID,
    provider: 'Internet 3',
    planName: 'Internet 3 Rural Connect',
    imageUrl: 'https://via.placeholder.com/400x300?text=Internet+3+Rural',
    price: 399,
    gstRate: 18,
    installationAmount: 500,
    description: 'Affordable internet solution for rural areas with good connectivity.',
  },
  {
    id: 11,
    organizationId: MOCK_ORGANIZATION_ID,
    provider: 'Internet 3',
    planName: 'Internet 3 Home Plus',
    imageUrl: 'https://via.placeholder.com/400x300?text=Internet+3+Home',
    price: 549,
    gstRate: 18,
    installationAmount: 500,
    description: 'Enhanced home internet connection with better speeds and coverage.',
  },
  {
    id: 12,
    organizationId: MOCK_ORGANIZATION_ID,
    provider: 'Internet 3',
    planName: 'Internet 3 Business',
    imageUrl: 'https://via.placeholder.com/400x300?text=Internet+3+Business',
    price: 799,
    gstRate: 18,
    installationAmount: 1000,
    description: 'Business-grade internet connection with dedicated support and reliability.',
  },
];

// Helper function to generate dates
const getDateString = (daysAgo: number): string => {
  const date = new Date();
  date.setDate(date.getDate() - daysAgo);
  return date.toISOString();
};

// Mock Customers - Payment Collection System applies to ALL product types (SaaS Ready)
export const mockCustomers: Customer[] = [
  {
    id: 1,
    organizationId: MOCK_ORGANIZATION_ID,
    name: 'Rajesh Kumar',
    email: 'rajesh.kumar@example.com',
    mobile: '9876543210',
    password: 'password123',
    connectionType: 'Cable',
    package: 'Cable Basic 50 Mbps',
    status: 'Active',
    description: 'Long-term customer, very satisfied with service.',
    address: {
      line1: '123 Main Street',
      line2: 'Near City Park',
      city: 'Mumbai',
      state: 'Maharashtra',
      country: 'India',
    },
    createdAt: getDateString(45),
    paymentStatus: 'paid',
    paymentDescription: 'Monthly bill paid via UPI on 15th.',
    paymentUpdatedAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
    paymentMethod: 'upi',
    collectedAmount: 589,
    balanceAmount: 0,
    boxNumber: 'BOX-001',
    stbNumber: 'STB-MH-001',
    canCafId: 'CAN-2024-00001',
    cin: 'CIN-MH-001',
    area: 'Andheri West',
  },
  {
    id: 2,
    organizationId: MOCK_ORGANIZATION_ID,
    name: 'Naresh',
    email: 'naresh@example.com',
    mobile: '9876543211',
    password: 'password123',
    connectionType: 'Internet 1',
    package: 'Internet 1 Fiber Basic',
    status: 'Active',
    description: 'New customer, installation completed last month.',
    address: {
      line1: '456 Park Avenue',
      line2: 'Block A',
      city: 'Delhi',
      state: 'Delhi',
      country: 'India',
    },
    createdAt: getDateString(25),
    paymentStatus: 'not_paid',
    area: 'Connaught Place',
  },
  {
    id: 3,
    organizationId: MOCK_ORGANIZATION_ID,
    name: 'Amit Patel',
    email: 'amit.patel@example.com',
    mobile: '9876543212',
    password: 'password123',
    connectionType: 'Internet 2',
    package: 'Internet 2 Express 75 Mbps',
    status: 'Inactive',
    description: 'Service temporarily suspended due to payment issues.',
    address: {
      line1: '789 Tech Road',
      line2: 'Sector 5',
      city: 'Bangalore',
      state: 'Karnataka',
      country: 'India',
    },
    createdAt: getDateString(60),
    paymentStatus: 'not_paid',
    balanceAmount: 707,
    area: 'Koramangala',
  },
  {
    id: 4,
    organizationId: MOCK_ORGANIZATION_ID,
    name: 'Sneha Reddy',
    email: 'sneha.reddy@example.com',
    mobile: '9876543213',
    password: 'password123',
    connectionType: 'Cable',
    package: 'Cable Premium 100 Mbps',
    status: 'Inactive',
    description: 'Upgraded to premium plan recently.',
    address: {
      line1: '321 Business Park',
      line2: 'Floor 3',
      city: 'Hyderabad',
      state: 'Telangana',
      country: 'India',
    },
    createdAt: getDateString(15),
    paymentStatus: 'not_paid',
    paymentDescription: 'Pending: December bill.',
    paymentUpdatedAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    balanceAmount: 943,
    boxNumber: 'BOX-004',
    stbNumber: 'STB-TS-004',
    canCafId: 'CAN-2024-00004',
    area: 'Banjara Hills',
  },
  {
    id: 5,
    organizationId: MOCK_ORGANIZATION_ID,
    name: 'Vikram Singh',
    email: 'vikram.singh@example.com',
    mobile: '9876543214',
    password: 'password123',
    connectionType: 'Internet 3',
    package: 'Internet 3 Rural Connect',
    status: 'Active',
    description: 'Rural area customer, good connectivity.',
    address: {
      line1: 'Village Road',
      line2: 'Near Post Office',
      city: 'Pune',
      state: 'Maharashtra',
      country: 'India',
    },
    createdAt: getDateString(5),
    paymentStatus: 'paid',
    paymentMethod: 'cash',
    collectedAmount: 471,
    balanceAmount: 0,
    paymentDescription: 'Paid in cash at local office.',
    paymentUpdatedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    area: 'Wakad',
  },
  {
    id: 6,
    organizationId: MOCK_ORGANIZATION_ID,
    name: 'Anjali Mehta',
    email: 'anjali.mehta@example.com',
    mobile: '9876543215',
    password: 'password123',
    connectionType: 'Internet 1',
    package: 'Internet 1 Fiber Plus',
    status: 'Active',
    description: 'Regular customer, always pays on time.',
    address: {
      line1: '567 Residential Complex',
      line2: 'Tower B',
      city: 'Chennai',
      state: 'Tamil Nadu',
      country: 'India',
    },
    createdAt: getDateString(30),
    paymentStatus: 'paid',
    paymentMethod: 'upi',
    collectedAmount: 825,
    balanceAmount: 0,
    paymentDescription: 'Auto-paid via Google Pay.',
    paymentUpdatedAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    area: 'T. Nagar',
  },
  {
    id: 7,
    organizationId: MOCK_ORGANIZATION_ID,
    name: 'Rahul Verma',
    email: 'rahul.verma@example.com',
    mobile: '9876543216',
    password: 'password123',
    connectionType: 'Internet 2',
    package: 'Internet 2 Speed 150 Mbps',
    status: 'Active',
    description: 'Business customer, requires high-speed connection.',
    address: {
      line1: '890 Corporate Avenue',
      line2: 'Suite 201',
      city: 'Gurgaon',
      state: 'Haryana',
      country: 'India',
    },
    createdAt: getDateString(8),
    paymentStatus: 'paid',
    paymentMethod: 'card',
    collectedAmount: 1061,
    balanceAmount: 0,
    paymentDescription: 'Paid by credit card.',
    paymentUpdatedAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    gstin: '06AABCT1234C1ZN',
    area: 'DLF Cyber City',
  },
  {
    id: 8,
    organizationId: MOCK_ORGANIZATION_ID,
    name: 'Kavita Nair',
    email: 'kavita.nair@example.com',
    mobile: '9876543217',
    password: 'password123',
    connectionType: 'Cable',
    package: 'Cable Ultra 200 Mbps',
    status: 'Active',
    description: 'Power user, needs ultra-fast speeds for work.',
    address: {
      line1: '234 Tech Hub',
      line2: 'Unit 15',
      city: 'Noida',
      state: 'Uttar Pradesh',
      country: 'India',
    },
    createdAt: getDateString(12),
    paymentStatus: 'paid',
    paymentDescription: 'Paid in full at office.',
    paymentUpdatedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    paymentMethod: 'cash',
    collectedAmount: 1533,
    balanceAmount: 0,
    boxNumber: 'BOX-008',
    stbNumber: 'STB-UP-008',
    canCafId: 'CAN-2024-00008',
    cin: 'CIN-UP-008',
    area: 'Sector 62',
  },
  {
    id: 9,
    organizationId: MOCK_ORGANIZATION_ID,
    name: 'Mohit Agarwal',
    email: 'mohit.agarwal@example.com',
    mobile: '9876543218',
    password: 'password123',
    connectionType: 'Internet 1',
    package: 'Internet 1 Fiber Premium',
    status: 'Inactive',
    description: 'Service disconnected, customer moved to different city.',
    address: {
      line1: '345 Green Valley',
      line2: 'Apartment 4B',
      city: 'Kolkata',
      state: 'West Bengal',
      country: 'India',
    },
    createdAt: getDateString(90),
    paymentStatus: 'not_paid',
  },
  {
    id: 10,
    organizationId: MOCK_ORGANIZATION_ID,
    name: 'Divya Joshi',
    email: 'divya.joshi@example.com',
    mobile: '9876543219',
    password: 'password123',
    connectionType: 'Internet 3',
    package: 'Internet 3 Home Plus',
    status: 'Active',
    description: 'Home user, satisfied with current plan.',
    address: {
      line1: '678 Suburban Lane',
      line2: 'House No. 12',
      city: 'Ahmedabad',
      state: 'Gujarat',
      country: 'India',
    },
    createdAt: getDateString(20),
    paymentStatus: 'not_paid',
  },
  {
    id: 11,
    organizationId: MOCK_ORGANIZATION_ID,
    name: 'Arjun Malhotra',
    email: 'arjun.malhotra@example.com',
    mobile: '9876543220',
    password: 'password123',
    connectionType: 'Internet 2',
    package: 'Internet 2 Turbo 300 Mbps',
    status: 'Active',
    description: 'Gaming enthusiast, requires low latency connection.',
    address: {
      line1: '901 Gaming Street',
      line2: 'Flat 302',
      city: 'Bangalore',
      state: 'Karnataka',
      country: 'India',
    },
    createdAt: getDateString(3),
    paymentStatus: 'not_paid',
  },
  {
    id: 12,
    organizationId: MOCK_ORGANIZATION_ID,
    name: 'Pooja Desai',
    email: 'pooja.desai@example.com',
    mobile: '9876543221',
    password: 'password123',
    connectionType: 'Cable',
    package: 'Cable Basic 50 Mbps',
    status: 'Active',
    description: 'Budget-conscious customer, happy with basic plan.',
    address: {
      line1: '112 Affordable Housing',
      line2: 'Block C',
      city: 'Surat',
      state: 'Gujarat',
      country: 'India',
    },
    createdAt: getDateString(18),
    paymentStatus: 'not_paid',
  },
  {
    id: 13,
    organizationId: MOCK_ORGANIZATION_ID,
    name: 'Suresh Iyer',
    email: 'suresh.iyer@example.com',
    mobile: '9876543222',
    password: 'password123',
    connectionType: 'Internet 1',
    package: 'Internet 1 Fiber Basic',
    status: 'Inactive',
    description: 'Temporary disconnection, will reconnect next month.',
    address: {
      line1: '223 Temple Road',
      line2: 'Near Market',
      city: 'Coimbatore',
      state: 'Tamil Nadu',
      country: 'India',
    },
    createdAt: getDateString(75),
    paymentStatus: 'not_paid',
  },
  {
    id: 14,
    organizationId: MOCK_ORGANIZATION_ID,
    name: 'Meera Krishnan',
    email: 'meera.krishnan@example.com',
    mobile: '9876543223',
    password: 'password123',
    connectionType: 'Internet 3',
    package: 'Internet 3 Business',
    status: 'Active',
    description: 'Small business owner, needs reliable connection for operations.',
    address: {
      line1: '334 Commercial Street',
      line2: 'Shop No. 5',
      city: 'Kochi',
      state: 'Kerala',
      country: 'India',
    },
    createdAt: getDateString(10),
    paymentStatus: 'not_paid',
  },
  {
    id: 15,
    organizationId: MOCK_ORGANIZATION_ID,
    name: 'Nikhil Kapoor',
    email: 'nikhil.kapoor@example.com',
    mobile: '9876543224',
    password: 'password123',
    connectionType: 'Cable',
    package: 'Cable Premium 100 Mbps',
    status: 'Active',
    description: 'Streaming enthusiast, upgraded for better quality.',
    address: {
      line1: '445 Entertainment Avenue',
      line2: 'Residency 8',
      city: 'Mumbai',
      state: 'Maharashtra',
      country: 'India',
    },
    createdAt: getDateString(7),
    paymentStatus: 'not_paid',
  },
  {
    id: 16,
    organizationId: MOCK_ORGANIZATION_ID,
    name: 'Riya Banerjee',
    email: 'riya.banerjee@example.com',
    mobile: '9876543225',
    password: 'password123',
    connectionType: 'Internet 2',
    package: 'Internet 2 Express 75 Mbps',
    status: 'Active',
    description: 'Student, needs internet for online classes.',
    address: {
      line1: '556 College Road',
      line2: 'Hostel Block',
      city: 'Pune',
      state: 'Maharashtra',
      country: 'India',
    },
    createdAt: getDateString(22),
    paymentStatus: 'not_paid',
  },
  {
    id: 17,
    organizationId: MOCK_ORGANIZATION_ID,
    name: 'Karan Thakur',
    email: 'karan.thakur@example.com',
    mobile: '9876543226',
    password: 'password123',
    connectionType: 'Internet 1',
    package: 'Internet 1 Fiber Plus',
    status: 'Active',
    description: 'Remote worker, depends on stable connection.',
    address: {
      line1: '667 Work From Home',
      line2: 'Apartment 9A',
      city: 'Jaipur',
      state: 'Rajasthan',
      country: 'India',
    },
    createdAt: getDateString(14),
    paymentStatus: 'not_paid',
  },
  {
    id: 18,
    organizationId: MOCK_ORGANIZATION_ID,
    name: 'Shreya Menon',
    email: 'shreya.menon@example.com',
    mobile: '9876543227',
    password: 'password123',
    connectionType: 'Internet 3',
    package: 'Internet 3 Rural Connect',
    status: 'Inactive',
    description: 'Service suspended due to area maintenance.',
    address: {
      line1: '778 Village Main Road',
      line2: 'House No. 23',
      city: 'Thrissur',
      state: 'Kerala',
      country: 'India',
    },
    createdAt: getDateString(50),
    paymentStatus: 'not_paid',
  },
  {
    id: 19,
    organizationId: MOCK_ORGANIZATION_ID,
    name: 'Aditya Rao',
    email: 'aditya.rao@example.com',
    mobile: '9876543228',
    password: 'password123',
    connectionType: 'Cable',
    package: 'Cable Ultra 200 Mbps',
    status: 'Active',
    description: 'Tech professional, requires high-speed for development work.',
    address: {
      line1: '889 Developer Hub',
      line2: 'Flat 501',
      city: 'Bangalore',
      state: 'Karnataka',
      country: 'India',
    },
    createdAt: getDateString(2),
    paymentStatus: 'not_paid',
  },
  {
    id: 20,
    organizationId: MOCK_ORGANIZATION_ID,
    name: 'Neha Gupta',
    email: 'neha.gupta@example.com',
    mobile: '9876543229',
    password: 'password123',
    connectionType: 'Internet 2',
    package: 'Internet 2 Speed 150 Mbps',
    status: 'Active',
    description: 'Content creator, needs fast upload speeds.',
    address: {
      line1: '990 Content Studio',
      line2: 'Unit 7',
      city: 'Mumbai',
      state: 'Maharashtra',
      country: 'India',
    },
    createdAt: getDateString(1),
    paymentStatus: 'not_paid',
  },
  {
    id: 21,
    organizationId: MOCK_ORGANIZATION_ID,
    name: 'Rohit Sharma',
    email: 'rohit.sharma@example.com',
    mobile: '9876543230',
    password: 'password123',
    connectionType: 'Internet 1',
    package: 'Internet 1 Fiber Premium',
    status: 'Active',
    description: 'Family plan, multiple devices connected.',
    address: {
      line1: '101 Family Home',
      line2: 'Ground Floor',
      city: 'Delhi',
      state: 'Delhi',
      country: 'India',
    },
    createdAt: getDateString(6),
    paymentStatus: 'not_paid',
  },
  {
    id: 22,
    organizationId: MOCK_ORGANIZATION_ID,
    name: 'Ananya Das',
    email: 'ananya.das@example.com',
    mobile: '9876543231',
    password: 'password123',
    connectionType: 'Internet 3',
    package: 'Internet 3 Home Plus',
    status: 'Active',
    description: 'New customer, just installed last week.',
    address: {
      line1: '202 New Colony',
      line2: 'House No. 45',
      city: 'Bhubaneswar',
      state: 'Odisha',
      country: 'India',
    },
    createdAt: getDateString(4),
    paymentStatus: 'not_paid',
  },
];

// ── Per-Org Mock Plans (non-ISP) ──
export const mockPlansExtra: Plan[] = [
  // org_002 Retail Plans
  { id: 101, organizationId: 'org_002', provider: 'Clothing', planName: 'Silver Member', imageUrl: '', price: 999, gstRate: 18, installationAmount: 0, description: 'Basic loyalty membership with 5% discount on all purchases.' },
  { id: 102, organizationId: 'org_002', provider: 'Clothing', planName: 'Gold Member', imageUrl: '', price: 1999, gstRate: 18, installationAmount: 0, description: 'Gold loyalty membership with 10% discount and priority service.' },
  { id: 103, organizationId: 'org_002', provider: 'Electronics', planName: 'Premium Member', imageUrl: '', price: 3999, gstRate: 18, installationAmount: 0, description: 'Premium loyalty with 15% discount, free delivery and extended warranty.' },
  // org_003 Salon Plans
  { id: 104, organizationId: 'org_003', provider: 'Hair Services', planName: 'Basic Membership 1 Month', imageUrl: '', price: 1500, gstRate: 18, installationAmount: 0, description: 'Monthly salon membership with unlimited basic services.' },
  { id: 105, organizationId: 'org_003', provider: 'Spa Treatments', planName: 'Premium Membership 3 Month', imageUrl: '', price: 3999, gstRate: 18, installationAmount: 0, description: 'Quarterly membership with spa sessions and hair treatments.' },
  { id: 106, organizationId: 'org_003', provider: 'Spa Treatments', planName: 'VIP Annual Package', imageUrl: '', price: 12999, gstRate: 18, installationAmount: 0, description: 'Annual VIP package with all services included and 20% discount.' },
  // org_004 Restaurant Plans
  { id: 107, organizationId: 'org_004', provider: 'Food', planName: 'Lunch Package', imageUrl: '', price: 2500, gstRate: 5, installationAmount: 0, description: 'Monthly lunch package — 22 working days lunch for one person.' },
  { id: 108, organizationId: 'org_004', provider: 'Food', planName: 'Family Dinner Package', imageUrl: '', price: 4999, gstRate: 5, installationAmount: 0, description: 'Monthly family dinner package for up to 4 members.' },
  // org_005 Healthcare Plans
  { id: 109, organizationId: 'org_005', provider: 'Medical Services', planName: 'Basic Health Plan', imageUrl: '', price: 999, gstRate: 0, installationAmount: 0, description: 'Annual basic health plan with 2 free consultations and 10% on medicines.' },
  { id: 110, organizationId: 'org_005', provider: 'Medical Services', planName: 'Premium Health Plan', imageUrl: '', price: 2499, gstRate: 0, installationAmount: 0, description: 'Annual premium plan with 6 consultations, lab tests, and 20% on medicines.' },
  { id: 111, organizationId: 'org_005', provider: 'Medical Services', planName: 'Senior Care Plan', imageUrl: '', price: 1999, gstRate: 0, installationAmount: 0, description: 'Annual senior care plan with home visit options and priority care.' },
  // org_006 Gym Plans
  { id: 112, organizationId: 'org_006', provider: 'Memberships', planName: 'Monthly Membership', imageUrl: '', price: 999, gstRate: 18, installationAmount: 500, description: 'Month-to-month gym membership with full facility access.' },
  { id: 113, organizationId: 'org_006', provider: 'Memberships', planName: 'Quarterly Membership', imageUrl: '', price: 2499, gstRate: 18, installationAmount: 0, description: '3-month gym membership with group classes included.' },
  { id: 114, organizationId: 'org_006', provider: 'Memberships', planName: 'Annual Membership', imageUrl: '', price: 7999, gstRate: 18, installationAmount: 0, description: 'Annual membership with unlimited access, 2 PT sessions per month.' },
  { id: 115, organizationId: 'org_006', provider: 'Personal Training', planName: 'PT Package 12 Sessions', imageUrl: '', price: 5999, gstRate: 18, installationAmount: 0, description: 'Personal training package — 12 one-on-one sessions with a certified trainer.' },
];

// ── Per-Org Mock Customers (non-ISP) ──
export const mockCustomersExtra: Customer[] = [
  // org_002 Retail customers
  { id: 101, organizationId: 'org_002', name: 'Priya Sharma', email: 'priya.sharma@example.com', mobile: '9800001001', password: 'password123', connectionType: 'Clothing', package: 'Gold Member', status: 'Active', address: { line1: '12 MG Road', line2: '', city: 'Bangalore', state: 'Karnataka', country: 'India' }, createdAt: getDateString(120), paymentStatus: 'paid', collectedAmount: 2358, balanceAmount: 0, loyaltyPoints: 2450 },
  { id: 102, organizationId: 'org_002', name: 'Ravi Menon', email: 'ravi.menon@example.com', mobile: '9800001002', password: 'password123', connectionType: 'Electronics', package: 'Premium Member', status: 'Active', address: { line1: '45 Brigade Road', line2: '', city: 'Bangalore', state: 'Karnataka', country: 'India' }, createdAt: getDateString(90), paymentStatus: 'paid', collectedAmount: 4718, balanceAmount: 0, loyaltyPoints: 3890 },
  { id: 103, organizationId: 'org_002', name: 'Sunita Patel', email: 'sunita.patel@example.com', mobile: '9800001003', password: 'password123', connectionType: 'Clothing', package: 'Silver Member', status: 'Active', address: { line1: '78 Commercial Street', line2: '', city: 'Bangalore', state: 'Karnataka', country: 'India' }, createdAt: getDateString(30), paymentStatus: 'not_paid', balanceAmount: 1178, loyaltyPoints: 650 },
  { id: 104, organizationId: 'org_002', name: 'Deepak Joshi', email: 'deepak.joshi@example.com', mobile: '9800001004', password: 'password123', connectionType: 'Electronics', package: 'Gold Member', status: 'Inactive', address: { line1: '90 Residency Road', line2: '', city: 'Bangalore', state: 'Karnataka', country: 'India' }, createdAt: getDateString(200), paymentStatus: 'not_paid', balanceAmount: 2358, loyaltyPoints: 1800 },
  { id: 105, organizationId: 'org_002', name: 'Anjana Kumar', email: 'anjana.kumar@example.com', mobile: '9800001005', password: 'password123', connectionType: 'Clothing', package: 'Silver Member', status: 'Active', address: { line1: '34 Indiranagar', line2: '', city: 'Bangalore', state: 'Karnataka', country: 'India' }, createdAt: getDateString(15), paymentStatus: 'paid', collectedAmount: 1178, balanceAmount: 0, loyaltyPoints: 320 },
  // org_003 Salon customers
  { id: 106, organizationId: 'org_003', name: 'Kavya Reddy', email: 'kavya.reddy@example.com', mobile: '9800002001', password: 'password123', connectionType: 'Hair Services', package: 'Premium Membership 3 Month', status: 'Active', address: { line1: '22 Jubilee Hills', line2: '', city: 'Hyderabad', state: 'Telangana', country: 'India' }, createdAt: getDateString(80), paymentStatus: 'paid', collectedAmount: 4718, balanceAmount: 0 },
  { id: 107, organizationId: 'org_003', name: 'Meera Pillai', email: 'meera.pillai@example.com', mobile: '9800002002', password: 'password123', connectionType: 'Spa Treatments', package: 'VIP Annual Package', status: 'Active', address: { line1: '56 Banjara Hills', line2: '', city: 'Hyderabad', state: 'Telangana', country: 'India' }, createdAt: getDateString(300), paymentStatus: 'paid', collectedAmount: 15338, balanceAmount: 0 },
  { id: 108, organizationId: 'org_003', name: 'Nisha Verma', email: 'nisha.verma@example.com', mobile: '9800002003', password: 'password123', connectionType: 'Hair Services', package: 'Basic Membership 1 Month', status: 'Active', address: { line1: '11 Film Nagar', line2: '', city: 'Hyderabad', state: 'Telangana', country: 'India' }, createdAt: getDateString(10), paymentStatus: 'not_paid', balanceAmount: 1770 },
  { id: 109, organizationId: 'org_003', name: 'Rekha Iyer', email: 'rekha.iyer@example.com', mobile: '9800002004', password: 'password123', connectionType: 'Spa Treatments', package: 'Premium Membership 3 Month', status: 'Inactive', address: { line1: '33 Madhapur', line2: '', city: 'Hyderabad', state: 'Telangana', country: 'India' }, createdAt: getDateString(150), paymentStatus: 'not_paid', balanceAmount: 4718 },
  { id: 110, organizationId: 'org_003', name: 'Shalini Das', email: 'shalini.das@example.com', mobile: '9800002005', password: 'password123', connectionType: 'Hair Services', package: 'Basic Membership 1 Month', status: 'Active', address: { line1: '7 Begumpet', line2: '', city: 'Hyderabad', state: 'Telangana', country: 'India' }, createdAt: getDateString(5), paymentStatus: 'paid', collectedAmount: 1770, balanceAmount: 0 },
  // org_004 Restaurant customers
  { id: 111, organizationId: 'org_004', name: 'Arjun Nair', email: 'arjun.nair@example.com', mobile: '9800003001', password: 'password123', connectionType: 'Food', package: 'Lunch Package', status: 'Active', address: { line1: '18 MG Road', line2: '', city: 'Kochi', state: 'Kerala', country: 'India' }, createdAt: getDateString(60), paymentStatus: 'paid', collectedAmount: 2950, balanceAmount: 0 },
  { id: 112, organizationId: 'org_004', name: 'Divya Krishnan', email: 'divya.krishnan@example.com', mobile: '9800003002', password: 'password123', connectionType: 'Food', package: 'Family Dinner Package', status: 'Active', address: { line1: '45 Marine Drive', line2: '', city: 'Kochi', state: 'Kerala', country: 'India' }, createdAt: getDateString(30), paymentStatus: 'paid', collectedAmount: 5248, balanceAmount: 0 },
  { id: 113, organizationId: 'org_004', name: 'Suresh Babu', email: 'suresh.babu@example.com', mobile: '9800003003', password: 'password123', connectionType: 'Food', package: 'Lunch Package', status: 'Active', address: { line1: '99 Ernakulam', line2: '', city: 'Kochi', state: 'Kerala', country: 'India' }, createdAt: getDateString(7), paymentStatus: 'not_paid', balanceAmount: 2950 },
  { id: 114, organizationId: 'org_004', name: 'Latha Menon', email: 'latha.menon@example.com', mobile: '9800003004', password: 'password123', connectionType: 'Food', package: 'Family Dinner Package', status: 'Inactive', address: { line1: '22 Kakkanad', line2: '', city: 'Kochi', state: 'Kerala', country: 'India' }, createdAt: getDateString(180), paymentStatus: 'not_paid', balanceAmount: 5248 },
  // org_005 Healthcare customers (patients)
  { id: 115, organizationId: 'org_005', name: 'Gopal Rao', email: 'gopal.rao@example.com', mobile: '9800004001', password: 'password123', connectionType: 'Medical Services', package: 'Premium Health Plan', status: 'Active', address: { line1: '5 Anna Nagar', line2: '', city: 'Chennai', state: 'Tamil Nadu', country: 'India' }, createdAt: getDateString(365), paymentStatus: 'paid', collectedAmount: 2499, balanceAmount: 0 },
  { id: 116, organizationId: 'org_005', name: 'Usha Natarajan', email: 'usha.natarajan@example.com', mobile: '9800004002', password: 'password123', connectionType: 'Medical Services', package: 'Senior Care Plan', status: 'Active', address: { line1: '88 T Nagar', line2: '', city: 'Chennai', state: 'Tamil Nadu', country: 'India' }, createdAt: getDateString(200), paymentStatus: 'paid', collectedAmount: 1999, balanceAmount: 0 },
  { id: 117, organizationId: 'org_005', name: 'Babu Subramanian', email: 'babu.s@example.com', mobile: '9800004003', password: 'password123', connectionType: 'Medicines', package: 'Basic Health Plan', status: 'Active', address: { line1: '12 Adyar', line2: '', city: 'Chennai', state: 'Tamil Nadu', country: 'India' }, createdAt: getDateString(90), paymentStatus: 'not_paid', balanceAmount: 999 },
  { id: 118, organizationId: 'org_005', name: 'Saroja Devi', email: 'saroja.devi@example.com', mobile: '9800004004', password: 'password123', connectionType: 'Medical Services', package: 'Senior Care Plan', status: 'Inactive', address: { line1: '33 Mylapore', line2: '', city: 'Chennai', state: 'Tamil Nadu', country: 'India' }, createdAt: getDateString(400), paymentStatus: 'not_paid', balanceAmount: 1999 },
  { id: 119, organizationId: 'org_005', name: 'Prakash Venkat', email: 'prakash.venkat@example.com', mobile: '9800004005', password: 'password123', connectionType: 'Medical Services', package: 'Premium Health Plan', status: 'Active', address: { line1: '67 Velachery', line2: '', city: 'Chennai', state: 'Tamil Nadu', country: 'India' }, createdAt: getDateString(45), paymentStatus: 'paid', collectedAmount: 2499, balanceAmount: 0 },
  // org_006 Gym customers (members)
  { id: 120, organizationId: 'org_006', name: 'Aditya Kulkarni', email: 'aditya.k@example.com', mobile: '9800005001', password: 'password123', connectionType: 'Memberships', package: 'Annual Membership', status: 'Active', address: { line1: '5 Koregaon Park', line2: '', city: 'Pune', state: 'Maharashtra', country: 'India' }, createdAt: getDateString(300), paymentStatus: 'paid', collectedAmount: 9438, balanceAmount: 0 },
  { id: 121, organizationId: 'org_006', name: 'Pooja Deshmukh', email: 'pooja.d@example.com', mobile: '9800005002', password: 'password123', connectionType: 'Memberships', package: 'Quarterly Membership', status: 'Active', address: { line1: '22 Viman Nagar', line2: '', city: 'Pune', state: 'Maharashtra', country: 'India' }, createdAt: getDateString(60), paymentStatus: 'paid', collectedAmount: 2948, balanceAmount: 0 },
  { id: 122, organizationId: 'org_006', name: 'Sanjay Patil', email: 'sanjay.patil@example.com', mobile: '9800005003', password: 'password123', connectionType: 'Personal Training', package: 'PT Package 12 Sessions', status: 'Active', address: { line1: '78 Baner Road', line2: '', city: 'Pune', state: 'Maharashtra', country: 'India' }, createdAt: getDateString(20), paymentStatus: 'not_paid', balanceAmount: 7078 },
  { id: 123, organizationId: 'org_006', name: 'Neha Joshi', email: 'neha.joshi@example.com', mobile: '9800005004', password: 'password123', connectionType: 'Memberships', package: 'Monthly Membership', status: 'Active', address: { line1: '44 Kothrud', line2: '', city: 'Pune', state: 'Maharashtra', country: 'India' }, createdAt: getDateString(5), paymentStatus: 'paid', collectedAmount: 1178, balanceAmount: 0 },
  { id: 124, organizationId: 'org_006', name: 'Rahul Bhosale', email: 'rahul.bhosale@example.com', mobile: '9800005005', password: 'password123', connectionType: 'Memberships', package: 'Annual Membership', status: 'Inactive', address: { line1: '15 Aundh', line2: '', city: 'Pune', state: 'Maharashtra', country: 'India' }, createdAt: getDateString(400), paymentStatus: 'not_paid', balanceAmount: 9438 },
  { id: 125, organizationId: 'org_006', name: 'Smita Gaikwad', email: 'smita.g@example.com', mobile: '9800005006', password: 'password123', connectionType: 'Memberships', package: 'Quarterly Membership', status: 'Active', address: { line1: '9 Wakad', line2: '', city: 'Pune', state: 'Maharashtra', country: 'India' }, createdAt: getDateString(45), paymentStatus: 'paid', collectedAmount: 2948, balanceAmount: 0 },
];

// Mock Users (Admin/Employee). Password plain text for mock only.
// Each demo organization gets an admin login
export const mockUsers: User[] = [
  // ISP Cable (org_001)
  { id: 1, organizationId: 'org_001', name: 'ISP Admin', username: 'isp', password: 'test123', role: 'admin', status: 'active', createdAt: getDateString(365) },
  { id: 2, organizationId: 'org_001', name: 'ISP Employee', username: 'isp-emp', password: 'test123', role: 'employee', status: 'active', allowedModules: ['contacts', 'complaints'], createdAt: getDateString(180) },
  // Retail (org_002)
  { id: 3, organizationId: 'org_002', name: 'Retail Admin', username: 'retail', password: 'test123', role: 'admin', status: 'active', createdAt: getDateString(300) },
  // Salon & Spa (org_003)
  { id: 4, organizationId: 'org_003', name: 'Salon Admin', username: 'salon', password: 'test123', role: 'admin', status: 'active', createdAt: getDateString(300) },
  // Restaurant (org_004)
  { id: 5, organizationId: 'org_004', name: 'Restaurant Admin', username: 'restaurant', password: 'test123', role: 'admin', status: 'active', createdAt: getDateString(300) },
  // Healthcare Pharmacy (org_005)
  { id: 6, organizationId: 'org_005', name: 'Pharmacy Admin', username: 'pharmacy', password: 'test123', role: 'admin', status: 'active', createdAt: getDateString(300) },
  // Gym Fitness (org_006)
  { id: 7, organizationId: 'org_006', name: 'Gym Admin', username: 'gym', password: 'test123', role: 'admin', status: 'active', createdAt: getDateString(300) },
];

// Mock Complaints - Cable and Internet (internal ids unchanged; do not mix)
export const mockComplaints: Complaint[] = [
  {
    id: 1,
    organizationId: MOCK_ORGANIZATION_ID,
    customerId: 1,
    customerName: 'Rajesh Kumar',
    mobile: '9876543210',
    connectionType: 'Cable',
    customerDescription: 'Internet speed is very slow during evening hours. Connection drops frequently.',
    internalDescription: 'Checked connection logs. High traffic during peak hours. Investigating bandwidth allocation.',
    status: 'active',
    createdAt: getDateString(2),
  },
  {
    id: 2,
    organizationId: MOCK_ORGANIZATION_ID,
    customerId: 2,
    customerName: 'Naresh',
    mobile: '9876543211',
    connectionType: 'Internet 1',
    customerDescription: 'Billing issue - charged extra amount this month. Need clarification on bill.',
    internalDescription: 'Reviewing billing records. May be due to plan upgrade mid-month.',
    status: 'active',
    createdAt: getDateString(1),
  },
  {
    id: 3,
    organizationId: MOCK_ORGANIZATION_ID,
    customerId: 3,
    customerName: 'Amit Patel',
    mobile: '9876543212',
    connectionType: 'Internet 2',
    customerDescription: 'Connection not working since yesterday. No internet access at all.',
    internalDescription: 'Urgent - Sending technician today. Suspected fiber cut in area.',
    status: 'active',
    createdAt: getDateString(0),
  },
  {
    id: 4,
    organizationId: MOCK_ORGANIZATION_ID,
    customerId: 4,
    customerName: 'Sneha Reddy',
    mobile: '9876543213',
    connectionType: 'Cable',
    customerDescription: 'Router needs replacement. Current router keeps restarting.',
    internalDescription: 'Waiting for router stock. Expected delivery in 2 days.',
    status: 'on-hold',
    createdAt: getDateString(5),
  },
  {
    id: 5,
    organizationId: MOCK_ORGANIZATION_ID,
    customerId: 5,
    customerName: 'Vikram Singh',
    mobile: '9876543214',
    connectionType: 'Internet 3',
    customerDescription: 'Installation pending for 3 days. Need urgent installation.',
    internalDescription: 'Scheduled for tomorrow. Technician assigned.',
    status: 'active',
    createdAt: getDateString(3),
  },
  {
    id: 6,
    organizationId: MOCK_ORGANIZATION_ID,
    customerId: 6,
    customerName: 'Anjali Mehta',
    mobile: '9876543215',
    connectionType: 'Internet 1',
    customerDescription: 'Slow download speeds. Not getting promised 100 Mbps.',
    internalDescription: 'Testing connection speed. May need line optimization.',
    status: 'on-hold',
    createdAt: getDateString(7),
  },
  {
    id: 7,
    organizationId: MOCK_ORGANIZATION_ID,
    customerId: 7,
    customerName: 'Rahul Verma',
    mobile: '9876543216',
    connectionType: 'Internet 2',
    customerDescription: 'Connection issue resolved. Thank you for quick support.',
    internalDescription: 'Issue resolved by resetting ONT. Customer satisfied.',
    status: 'completed',
    createdAt: getDateString(10),
    closedAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
    // Mock closure image (base64 placeholder). Replace with real backend image URL later.
    closureImage: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mP8z8BQDwAEhQGAhKmMIQAAAABJRU5ErkJggg==',
  },
  {
    id: 8,
    organizationId: MOCK_ORGANIZATION_ID,
    customerId: 8,
    customerName: 'Kavita Nair',
    mobile: '9876543217',
    connectionType: 'Cable',
    customerDescription: 'Need to upgrade plan. Current plan not sufficient for work from home.',
    internalDescription: 'Contacted customer. Upgrading to 200 Mbps plan.',
    status: 'active',
    createdAt: getDateString(1),
  },
  {
    id: 9,
    organizationId: MOCK_ORGANIZATION_ID,
    customerId: 9,
    customerName: 'Mohit Agarwal',
    mobile: '9876543218',
    connectionType: 'Internet 1',
    customerDescription: 'Fiber cable cut due to construction work. Need repair.',
    internalDescription: 'Emergency repair team dispatched. ETA 4 hours.',
    status: 'active',
    createdAt: getDateString(0),
  },
  {
    id: 10,
    organizationId: MOCK_ORGANIZATION_ID,
    customerId: 10,
    customerName: 'Divya Joshi',
    mobile: '9876543219',
    connectionType: 'Internet 3',
    customerDescription: 'Payment gateway issue. Unable to pay online bill.',
    internalDescription: 'Payment gateway working. Customer can try alternative payment method.',
    status: 'on-hold',
    createdAt: getDateString(4),
  },
  {
    id: 11,
    organizationId: MOCK_ORGANIZATION_ID,
    customerId: 11,
    customerName: 'Arjun Malhotra',
    mobile: '9876543220',
    connectionType: 'Internet 2',
    customerDescription: 'High ping in online games. Connection unstable during gaming.',
    internalDescription: 'Checking latency. May need QoS configuration for gaming.',
    status: 'active',
    createdAt: getDateString(2),
  },
  {
    id: 12,
    organizationId: MOCK_ORGANIZATION_ID,
    customerId: 12,
    customerName: 'Pooja Desai',
    mobile: '9876543221',
    connectionType: 'Cable',
    customerDescription: 'Router configuration issue resolved. Working fine now.',
    internalDescription: 'Fixed router settings. Connection stable now.',
    status: 'completed',
    createdAt: getDateString(8),
    closedAt: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 13,
    organizationId: MOCK_ORGANIZATION_ID,
    customerId: 13,
    customerName: 'Suresh Iyer',
    mobile: '9876543222',
    connectionType: 'Internet 1',
    customerDescription: 'Service reconnection request. Want to resume connection.',
    internalDescription: 'Processing reconnection. Will activate within 24 hours.',
    status: 'active',
    createdAt: getDateString(1),
  },
  {
    id: 14,
    organizationId: MOCK_ORGANIZATION_ID,
    customerId: 14,
    customerName: 'Meera Krishnan',
    mobile: '9876543223',
    connectionType: 'Internet 3',
    customerDescription: 'Business connection needs dedicated IP address. Please provide.',
    internalDescription: 'Dedicated IP allocation in progress. Requires network configuration.',
    status: 'on-hold',
    createdAt: getDateString(6),
  },
  {
    id: 15,
    organizationId: MOCK_ORGANIZATION_ID,
    customerId: 15,
    customerName: 'Nikhil Kapoor',
    mobile: '9876543224',
    connectionType: 'Cable',
    customerDescription: 'Streaming quality poor. Buffering issues on Netflix and YouTube.',
    internalDescription: 'Investigating bandwidth allocation. May need to optimize streaming traffic.',
    status: 'active',
    createdAt: getDateString(0),
  },
  {
    id: 16,
    organizationId: MOCK_ORGANIZATION_ID,
    customerId: 16,
    customerName: 'Riya Banerjee',
    mobile: '9876543225',
    connectionType: 'Internet 2',
    customerDescription: 'Connection restored. Issue was from ISP side, now fixed.',
    internalDescription: 'Network maintenance completed. All services restored.',
    status: 'completed',
    createdAt: getDateString(12),
    closedAt: new Date(Date.now() - 12 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 17,
    organizationId: MOCK_ORGANIZATION_ID,
    customerId: 17,
    customerName: 'Karan Thakur',
    mobile: '9876543226',
    connectionType: 'Internet 1',
    customerDescription: 'Need to relocate connection to new address. Please arrange.',
    internalDescription: 'Relocation request received. Survey scheduled for next week.',
    status: 'active',
    createdAt: getDateString(2),
  },
  {
    id: 18,
    organizationId: MOCK_ORGANIZATION_ID,
    customerId: 18,
    customerName: 'Shreya Menon',
    mobile: '9876543227',
    connectionType: 'Internet 3',
    customerDescription: 'Technical support ticket resolved. Customer satisfied.',
    internalDescription: 'All issues resolved. Customer feedback positive.',
    status: 'completed',
    createdAt: getDateString(15),
    closedAt: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000).toISOString(),
  },
];
