// SaaS Ready - Fully Dynamic Product
import type { Plan, Customer, Complaint, User } from '@/models/types';
import { MOCK_ORGANIZATION_ID } from '@/models/types';

// Multi-tenant SaaS Isolation - All mock data scoped by organizationId.
// Products fully dynamic - no hardcoded service names. Mock uses product names from Products API.

// Mock Plans - provider = product name from Admin → Settings → Products
export const mockPlans: Plan[] = [
  {
    id: 1,
    organizationId: MOCK_ORGANIZATION_ID,
    provider: 'Cable',
    planName: 'Cable Basic 50 Mbps',
    imageUrl: 'https://via.placeholder.com/400x300?text=Cable+Basic',
    price: 499,
    gstRate: 18,
    installationAmount: 500,
    description: 'High-speed cable broadband connection with 50 Mbps download speed. Perfect for small families and home offices.',
  },
  {
    id: 2,
    organizationId: MOCK_ORGANIZATION_ID,
    provider: 'Cable',
    planName: 'Cable Premium 100 Mbps',
    imageUrl: 'https://via.placeholder.com/400x300?text=Cable+Premium',
    price: 799,
    gstRate: 18,
    installationAmount: 500,
    description: 'Premium cable broadband connection with 100 Mbps download speed. Ideal for streaming and gaming.',
  },
  {
    id: 3,
    organizationId: MOCK_ORGANIZATION_ID,
    provider: 'Cable',
    planName: 'Cable Ultra 200 Mbps',
    imageUrl: 'https://via.placeholder.com/400x300?text=Cable+Ultra',
    price: 1299,
    gstRate: 18,
    installationAmount: 1000,
    description: 'Ultra-fast cable broadband connection with 200 Mbps download speed. Perfect for heavy users and businesses.',
  },
  // Internet 1
  {
    id: 4,
    organizationId: MOCK_ORGANIZATION_ID,
    provider: 'Internet 1',
    planName: 'Internet 1 Fiber Basic',
    imageUrl: 'https://via.placeholder.com/400x300?text=Internet+1+Fiber',
    price: 449,
    gstRate: 18,
    installationAmount: 500,
    description: 'Reliable fiber connection with stable speeds and excellent coverage.',
  },
  {
    id: 5,
    organizationId: MOCK_ORGANIZATION_ID,
    provider: 'Internet 1',
    planName: 'Internet 1 Fiber Plus',
    imageUrl: 'https://via.placeholder.com/400x300?text=Internet+1+Plus',
    price: 699,
    gstRate: 18,
    installationAmount: 500,
    description: 'Enhanced fiber connection with better speeds and reliability.',
  },
  {
    id: 6,
    organizationId: MOCK_ORGANIZATION_ID,
    provider: 'Internet 1',
    planName: 'Internet 1 Fiber Premium',
    imageUrl: 'https://via.placeholder.com/400x300?text=Internet+1+Premium',
    price: 999,
    gstRate: 18,
    installationAmount: 1000,
    description: 'Premium fiber connection with high-speed internet for demanding users.',
  },
  // Internet 2
  {
    id: 7,
    organizationId: MOCK_ORGANIZATION_ID,
    provider: 'Internet 2',
    planName: 'Internet 2 Express 75 Mbps',
    imageUrl: 'https://via.placeholder.com/400x300?text=Internet+2+Express',
    price: 599,
    gstRate: 18,
    installationAmount: 500,
    description: 'Fast and reliable connection with 75 Mbps speed.',
  },
  {
    id: 8,
    organizationId: MOCK_ORGANIZATION_ID,
    provider: 'Internet 2',
    planName: 'Internet 2 Speed 150 Mbps',
    imageUrl: 'https://via.placeholder.com/400x300?text=Internet+2+Speed',
    price: 899,
    gstRate: 18,
    installationAmount: 500,
    description: 'High-speed connection with 150 Mbps for power users.',
  },
  {
    id: 9,
    organizationId: MOCK_ORGANIZATION_ID,
    provider: 'Internet 2',
    planName: 'Internet 2 Turbo 300 Mbps',
    imageUrl: 'https://via.placeholder.com/400x300?text=Internet+2+Turbo',
    price: 1499,
    gstRate: 18,
    installationAmount: 1000,
    description: 'Turbo-charged connection with blazing fast 300 Mbps speeds.',
  },
  // Internet 3
  {
    id: 10,
    organizationId: MOCK_ORGANIZATION_ID,
    provider: 'Internet 3',
    planName: 'Internet 3 Rural Connect',
    imageUrl: 'https://via.placeholder.com/400x300?text=Internet+3+Rural',
    price: 399,
    gstRate: 18,
    installationAmount: 500,
    description: 'Affordable internet solution for rural areas with good connectivity.',
  },
  {
    id: 11,
    organizationId: MOCK_ORGANIZATION_ID,
    provider: 'Internet 3',
    planName: 'Internet 3 Home Plus',
    imageUrl: 'https://via.placeholder.com/400x300?text=Internet+3+Home',
    price: 549,
    gstRate: 18,
    installationAmount: 500,
    description: 'Enhanced home internet connection with better speeds and coverage.',
  },
  {
    id: 12,
    organizationId: MOCK_ORGANIZATION_ID,
    provider: 'Internet 3',
    planName: 'Internet 3 Business',
    imageUrl: 'https://via.placeholder.com/400x300?text=Internet+3+Business',
    price: 799,
    gstRate: 18,
    installationAmount: 1000,
    description: 'Business-grade internet connection with dedicated support and reliability.',
  },
];

// Helper function to generate dates
const getDateString = (daysAgo: number): string => {
  const date = new Date();
  date.setDate(date.getDate() - daysAgo);
  return date.toISOString();
};

// Mock Customers - Payment Collection System applies to ALL product types (SaaS Ready)
export const mockCustomers: Customer[] = [
  {
    id: 1,
    organizationId: MOCK_ORGANIZATION_ID,
    name: 'Rajesh Kumar',
    email: 'rajesh.kumar@example.com',
    mobile: '9876543210',
    password: 'password123',
    connectionType: 'Cable',
    package: 'Cable Basic 50 Mbps',
    status: 'Active',
    description: 'Long-term customer, very satisfied with service.',
    address: {
      line1: '123 Main Street',
      line2: 'Near City Park',
      city: 'Mumbai',
      state: 'Maharashtra',
      country: 'India',
    },
    createdAt: getDateString(45),
    paymentStatus: 'paid',
    paymentDescription: 'Monthly bill paid via UPI on 15th.',
    paymentUpdatedAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
    paymentMethod: 'upi',
    collectedAmount: 589,
    balanceAmount: 0,
    boxNumber: 'BOX-001',
    stbNumber: 'STB-MH-001',
    canCafId: 'CAN-2024-00001',
    cin: 'CIN-MH-001',
    area: 'Andheri West',
  },
  {
    id: 2,
    organizationId: MOCK_ORGANIZATION_ID,
    name: 'Naresh',
    email: 'naresh@example.com',
    mobile: '9876543211',
    password: 'password123',
    connectionType: 'Internet 1',
    package: 'Internet 1 Fiber Basic',
    status: 'Active',
    description: 'New customer, installation completed last month.',
    address: {
      line1: '456 Park Avenue',
      line2: 'Block A',
      city: 'Delhi',
      state: 'Delhi',
      country: 'India',
    },
    createdAt: getDateString(25),
    paymentStatus: 'not_paid',
    area: 'Connaught Place',
  },
  {
    id: 3,
    organizationId: MOCK_ORGANIZATION_ID,
    name: 'Amit Patel',
    email: 'amit.patel@example.com',
    mobile: '9876543212',
    password: 'password123',
    connectionType: 'Internet 2',
    package: 'Internet 2 Express 75 Mbps',
    status: 'Inactive',
    description: 'Service temporarily suspended due to payment issues.',
    address: {
      line1: '789 Tech Road',
      line2: 'Sector 5',
      city: 'Bangalore',
      state: 'Karnataka',
      country: 'India',
    },
    createdAt: getDateString(60),
    paymentStatus: 'not_paid',
    balanceAmount: 707,
    area: 'Koramangala',
  },
  {
    id: 4,
    organizationId: MOCK_ORGANIZATION_ID,
    name: 'Sneha Reddy',
    email: 'sneha.reddy@example.com',
    mobile: '9876543213',
    password: 'password123',
    connectionType: 'Cable',
    package: 'Cable Premium 100 Mbps',
    status: 'Inactive',
    description: 'Upgraded to premium plan recently.',
    address: {
      line1: '321 Business Park',
      line2: 'Floor 3',
      city: 'Hyderabad',
      state: 'Telangana',
      country: 'India',
    },
    createdAt: getDateString(15),
    paymentStatus: 'not_paid',
    paymentDescription: 'Pending: December bill.',
    paymentUpdatedAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    balanceAmount: 943,
    boxNumber: 'BOX-004',
    stbNumber: 'STB-TS-004',
    canCafId: 'CAN-2024-00004',
    area: 'Banjara Hills',
  },
  {
    id: 5,
    organizationId: MOCK_ORGANIZATION_ID,
    name: 'Vikram Singh',
    email: 'vikram.singh@example.com',
    mobile: '9876543214',
    password: 'password123',
    connectionType: 'Internet 3',
    package: 'Internet 3 Rural Connect',
    status: 'Active',
    description: 'Rural area customer, good connectivity.',
    address: {
      line1: 'Village Road',
      line2: 'Near Post Office',
      city: 'Pune',
      state: 'Maharashtra',
      country: 'India',
    },
    createdAt: getDateString(5),
    paymentStatus: 'paid',
    paymentMethod: 'cash',
    collectedAmount: 471,
    balanceAmount: 0,
    paymentDescription: 'Paid in cash at local office.',
    paymentUpdatedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    area: 'Wakad',
  },
  {
    id: 6,
    organizationId: MOCK_ORGANIZATION_ID,
    name: 'Anjali Mehta',
    email: 'anjali.mehta@example.com',
    mobile: '9876543215',
    password: 'password123',
    connectionType: 'Internet 1',
    package: 'Internet 1 Fiber Plus',
    status: 'Active',
    description: 'Regular customer, always pays on time.',
    address: {
      line1: '567 Residential Complex',
      line2: 'Tower B',
      city: 'Chennai',
      state: 'Tamil Nadu',
      country: 'India',
    },
    createdAt: getDateString(30),
    paymentStatus: 'paid',
    paymentMethod: 'upi',
    collectedAmount: 825,
    balanceAmount: 0,
    paymentDescription: 'Auto-paid via Google Pay.',
    paymentUpdatedAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    area: 'T. Nagar',
  },
  {
    id: 7,
    organizationId: MOCK_ORGANIZATION_ID,
    name: 'Rahul Verma',
    email: 'rahul.verma@example.com',
    mobile: '9876543216',
    password: 'password123',
    connectionType: 'Internet 2',
    package: 'Internet 2 Speed 150 Mbps',
    status: 'Active',
    description: 'Business customer, requires high-speed connection.',
    address: {
      line1: '890 Corporate Avenue',
      line2: 'Suite 201',
      city: 'Gurgaon',
      state: 'Haryana',
      country: 'India',
    },
    createdAt: getDateString(8),
    paymentStatus: 'paid',
    paymentMethod: 'card',
    collectedAmount: 1061,
    balanceAmount: 0,
    paymentDescription: 'Paid by credit card.',
    paymentUpdatedAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    gstin: '06AABCT1234C1ZN',
    area: 'DLF Cyber City',
  },
  {
    id: 8,
    organizationId: MOCK_ORGANIZATION_ID,
    name: 'Kavita Nair',
    email: 'kavita.nair@example.com',
    mobile: '9876543217',
    password: 'password123',
    connectionType: 'Cable',
    package: 'Cable Ultra 200 Mbps',
    status: 'Active',
    description: 'Power user, needs ultra-fast speeds for work.',
    address: {
      line1: '234 Tech Hub',
      line2: 'Unit 15',
      city: 'Noida',
      state: 'Uttar Pradesh',
      country: 'India',
    },
    createdAt: getDateString(12),
    paymentStatus: 'paid',
    paymentDescription: 'Paid in full at office.',
    paymentUpdatedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    paymentMethod: 'cash',
    collectedAmount: 1533,
    balanceAmount: 0,
    boxNumber: 'BOX-008',
    stbNumber: 'STB-UP-008',
    canCafId: 'CAN-2024-00008',
    cin: 'CIN-UP-008',
    area: 'Sector 62',
  },
  {
    id: 9,
    organizationId: MOCK_ORGANIZATION_ID,
    name: 'Mohit Agarwal',
    email: 'mohit.agarwal@example.com',
    mobile: '9876543218',
    password: 'password123',
    connectionType: 'Internet 1',
    package: 'Internet 1 Fiber Premium',
    status: 'Inactive',
    description: 'Service disconnected, customer moved to different city.',
    address: {
      line1: '345 Green Valley',
      line2: 'Apartment 4B',
      city: 'Kolkata',
      state: 'West Bengal',
      country: 'India',
    },
    createdAt: getDateString(90),
    paymentStatus: 'not_paid',
  },
  {
    id: 10,
    organizationId: MOCK_ORGANIZATION_ID,
    name: 'Divya Joshi',
    email: 'divya.joshi@example.com',
    mobile: '9876543219',
    password: 'password123',
    connectionType: 'Internet 3',
    package: 'Internet 3 Home Plus',
    status: 'Active',
    description: 'Home user, satisfied with current plan.',
    address: {
      line1: '678 Suburban Lane',
      line2: 'House No. 12',
      city: 'Ahmedabad',
      state: 'Gujarat',
      country: 'India',
    },
    createdAt: getDateString(20),
    paymentStatus: 'not_paid',
  },
  {
    id: 11,
    organizationId: MOCK_ORGANIZATION_ID,
    name: 'Arjun Malhotra',
    email: 'arjun.malhotra@example.com',
    mobile: '9876543220',
    password: 'password123',
    connectionType: 'Internet 2',
    package: 'Internet 2 Turbo 300 Mbps',
    status: 'Active',
    description: 'Gaming enthusiast, requires low latency connection.',
    address: {
      line1: '901 Gaming Street',
      line2: 'Flat 302',
      city: 'Bangalore',
      state: 'Karnataka',
      country: 'India',
    },
    createdAt: getDateString(3),
    paymentStatus: 'not_paid',
  },
  {
    id: 12,
    organizationId: MOCK_ORGANIZATION_ID,
    name: 'Pooja Desai',
    email: 'pooja.desai@example.com',
    mobile: '9876543221',
    password: 'password123',
    connectionType: 'Cable',
    package: 'Cable Basic 50 Mbps',
    status: 'Active',
    description: 'Budget-conscious customer, happy with basic plan.',
    address: {
      line1: '112 Affordable Housing',
      line2: 'Block C',
      city: 'Surat',
      state: 'Gujarat',
      country: 'India',
    },
    createdAt: getDateString(18),
    paymentStatus: 'not_paid',
  },
  {
    id: 13,
    organizationId: MOCK_ORGANIZATION_ID,
    name: 'Suresh Iyer',
    email: 'suresh.iyer@example.com',
    mobile: '9876543222',
    password: 'password123',
    connectionType: 'Internet 1',
    package: 'Internet 1 Fiber Basic',
    status: 'Inactive',
    description: 'Temporary disconnection, will reconnect next month.',
    address: {
      line1: '223 Temple Road',
      line2: 'Near Market',
      city: 'Coimbatore',
      state: 'Tamil Nadu',
      country: 'India',
    },
    createdAt: getDateString(75),
    paymentStatus: 'not_paid',
  },
  {
    id: 14,
    organizationId: MOCK_ORGANIZATION_ID,
    name: 'Meera Krishnan',
    email: 'meera.krishnan@example.com',
    mobile: '9876543223',
    password: 'password123',
    connectionType: 'Internet 3',
    package: 'Internet 3 Business',
    status: 'Active',
    description: 'Small business owner, needs reliable connection for operations.',
    address: {
      line1: '334 Commercial Street',
      line2: 'Shop No. 5',
      city: 'Kochi',
      state: 'Kerala',
      country: 'India',
    },
    createdAt: getDateString(10),
    paymentStatus: 'not_paid',
  },
  {
    id: 15,
    organizationId: MOCK_ORGANIZATION_ID,
    name: 'Nikhil Kapoor',
    email: 'nikhil.kapoor@example.com',
    mobile: '9876543224',
    password: 'password123',
    connectionType: 'Cable',
    package: 'Cable Premium 100 Mbps',
    status: 'Active',
    description: 'Streaming enthusiast, upgraded for better quality.',
    address: {
      line1: '445 Entertainment Avenue',
      line2: 'Residency 8',
      city: 'Mumbai',
      state: 'Maharashtra',
      country: 'India',
    },
    createdAt: getDateString(7),
    paymentStatus: 'not_paid',
  },
  {
    id: 16,
    organizationId: MOCK_ORGANIZATION_ID,
    name: 'Riya Banerjee',
    email: 'riya.banerjee@example.com',
    mobile: '9876543225',
    password: 'password123',
    connectionType: 'Internet 2',
    package: 'Internet 2 Express 75 Mbps',
    status: 'Active',
    description: 'Student, needs internet for online classes.',
    address: {
      line1: '556 College Road',
      line2: 'Hostel Block',
      city: 'Pune',
      state: 'Maharashtra',
      country: 'India',
    },
    createdAt: getDateString(22),
    paymentStatus: 'not_paid',
  },
  {
    id: 17,
    organizationId: MOCK_ORGANIZATION_ID,
    name: 'Karan Thakur',
    email: 'karan.thakur@example.com',
    mobile: '9876543226',
    password: 'password123',
    connectionType: 'Internet 1',
    package: 'Internet 1 Fiber Plus',
    status: 'Active',
    description: 'Remote worker, depends on stable connection.',
    address: {
      line1: '667 Work From Home',
      line2: 'Apartment 9A',
      city: 'Jaipur',
      state: 'Rajasthan',
      country: 'India',
    },
    createdAt: getDateString(14),
    paymentStatus: 'not_paid',
  },
  {
    id: 18,
    organizationId: MOCK_ORGANIZATION_ID,
    name: 'Shreya Menon',
    email: 'shreya.menon@example.com',
    mobile: '9876543227',
    password: 'password123',
    connectionType: 'Internet 3',
    package: 'Internet 3 Rural Connect',
    status: 'Inactive',
    description: 'Service suspended due to area maintenance.',
    address: {
      line1: '778 Village Main Road',
      line2: 'House No. 23',
      city: 'Thrissur',
      state: 'Kerala',
      country: 'India',
    },
    createdAt: getDateString(50),
    paymentStatus: 'not_paid',
  },
  {
    id: 19,
    organizationId: MOCK_ORGANIZATION_ID,
    name: 'Aditya Rao',
    email: 'aditya.rao@example.com',
    mobile: '9876543228',
    password: 'password123',
    connectionType: 'Cable',
    package: 'Cable Ultra 200 Mbps',
    status: 'Active',
    description: 'Tech professional, requires high-speed for development work.',
    address: {
      line1: '889 Developer Hub',
      line2: 'Flat 501',
      city: 'Bangalore',
      state: 'Karnataka',
      country: 'India',
    },
    createdAt: getDateString(2),
    paymentStatus: 'not_paid',
  },
  {
    id: 20,
    organizationId: MOCK_ORGANIZATION_ID,
    name: 'Neha Gupta',
    email: 'neha.gupta@example.com',
    mobile: '9876543229',
    password: 'password123',
    connectionType: 'Internet 2',
    package: 'Internet 2 Speed 150 Mbps',
    status: 'Active',
    description: 'Content creator, needs fast upload speeds.',
    address: {
      line1: '990 Content Studio',
      line2: 'Unit 7',
      city: 'Mumbai',
      state: 'Maharashtra',
      country: 'India',
    },
    createdAt: getDateString(1),
    paymentStatus: 'not_paid',
  },
  {
    id: 21,
    organizationId: MOCK_ORGANIZATION_ID,
    name: 'Rohit Sharma',
    email: 'rohit.sharma@example.com',
    mobile: '9876543230',
    password: 'password123',
    connectionType: 'Internet 1',
    package: 'Internet 1 Fiber Premium',
    status: 'Active',
    description: 'Family plan, multiple devices connected.',
    address: {
      line1: '101 Family Home',
      line2: 'Ground Floor',
      city: 'Delhi',
      state: 'Delhi',
      country: 'India',
    },
    createdAt: getDateString(6),
    paymentStatus: 'not_paid',
  },
  {
    id: 22,
    organizationId: MOCK_ORGANIZATION_ID,
    name: 'Ananya Das',
    email: 'ananya.das@example.com',
    mobile: '9876543231',
    password: 'password123',
    connectionType: 'Internet 3',
    package: 'Internet 3 Home Plus',
    status: 'Active',
    description: 'New customer, just installed last week.',
    address: {
      line1: '202 New Colony',
      line2: 'House No. 45',
      city: 'Bhubaneswar',
      state: 'Odisha',
      country: 'India',
    },
    createdAt: getDateString(4),
    paymentStatus: 'not_paid',
  },
];

// Mock Users (Admin/Employee). Password plain text for mock only.
// Each demo organization gets an admin login
export const mockUsers: User[] = [
  // ISP Cable (org_001)
  { id: 1, organizationId: 'org_001', name: 'ISP Admin', username: 'isp', password: 'test123', role: 'admin', status: 'active', createdAt: getDateString(365) },
  { id: 2, organizationId: 'org_001', name: 'ISP Employee', username: 'isp-emp', password: 'test123', role: 'employee', status: 'active', allowedModules: ['contacts', 'complaints'], createdAt: getDateString(180) },
  // Retail (org_002)
  { id: 3, organizationId: 'org_002', name: 'Retail Admin', username: 'retail', password: 'test123', role: 'admin', status: 'active', createdAt: getDateString(300) },
  // Salon & Spa (org_003)
  { id: 4, organizationId: 'org_003', name: 'Salon Admin', username: 'salon', password: 'test123', role: 'admin', status: 'active', createdAt: getDateString(300) },
  // Restaurant (org_004)
  { id: 5, organizationId: 'org_004', name: 'Restaurant Admin', username: 'restaurant', password: 'test123', role: 'admin', status: 'active', createdAt: getDateString(300) },
  // Healthcare Pharmacy (org_005)
  { id: 6, organizationId: 'org_005', name: 'Pharmacy Admin', username: 'pharmacy', password: 'test123', role: 'admin', status: 'active', createdAt: getDateString(300) },
  // Gym Fitness (org_006)
  { id: 7, organizationId: 'org_006', name: 'Gym Admin', username: 'gym', password: 'test123', role: 'admin', status: 'active', createdAt: getDateString(300) },
];

// Mock Complaints - Cable and Internet (internal ids unchanged; do not mix)
export const mockComplaints: Complaint[] = [
  {
    id: 1,
    organizationId: MOCK_ORGANIZATION_ID,
    customerId: 1,
    customerName: 'Rajesh Kumar',
    mobile: '9876543210',
    connectionType: 'Cable',
    customerDescription: 'Internet speed is very slow during evening hours. Connection drops frequently.',
    internalDescription: 'Checked connection logs. High traffic during peak hours. Investigating bandwidth allocation.',
    status: 'active',
    createdAt: getDateString(2),
  },
  {
    id: 2,
    organizationId: MOCK_ORGANIZATION_ID,
    customerId: 2,
    customerName: 'Naresh',
    mobile: '9876543211',
    connectionType: 'Internet 1',
    customerDescription: 'Billing issue - charged extra amount this month. Need clarification on bill.',
    internalDescription: 'Reviewing billing records. May be due to plan upgrade mid-month.',
    status: 'active',
    createdAt: getDateString(1),
  },
  {
    id: 3,
    organizationId: MOCK_ORGANIZATION_ID,
    customerId: 3,
    customerName: 'Amit Patel',
    mobile: '9876543212',
    connectionType: 'Internet 2',
    customerDescription: 'Connection not working since yesterday. No internet access at all.',
    internalDescription: 'Urgent - Sending technician today. Suspected fiber cut in area.',
    status: 'active',
    createdAt: getDateString(0),
  },
  {
    id: 4,
    organizationId: MOCK_ORGANIZATION_ID,
    customerId: 4,
    customerName: 'Sneha Reddy',
    mobile: '9876543213',
    connectionType: 'Cable',
    customerDescription: 'Router needs replacement. Current router keeps restarting.',
    internalDescription: 'Waiting for router stock. Expected delivery in 2 days.',
    status: 'on-hold',
    createdAt: getDateString(5),
  },
  {
    id: 5,
    organizationId: MOCK_ORGANIZATION_ID,
    customerId: 5,
    customerName: 'Vikram Singh',
    mobile: '9876543214',
    connectionType: 'Internet 3',
    customerDescription: 'Installation pending for 3 days. Need urgent installation.',
    internalDescription: 'Scheduled for tomorrow. Technician assigned.',
    status: 'active',
    createdAt: getDateString(3),
  },
  {
    id: 6,
    organizationId: MOCK_ORGANIZATION_ID,
    customerId: 6,
    customerName: 'Anjali Mehta',
    mobile: '9876543215',
    connectionType: 'Internet 1',
    customerDescription: 'Slow download speeds. Not getting promised 100 Mbps.',
    internalDescription: 'Testing connection speed. May need line optimization.',
    status: 'on-hold',
    createdAt: getDateString(7),
  },
  {
    id: 7,
    organizationId: MOCK_ORGANIZATION_ID,
    customerId: 7,
    customerName: 'Rahul Verma',
    mobile: '9876543216',
    connectionType: 'Internet 2',
    customerDescription: 'Connection issue resolved. Thank you for quick support.',
    internalDescription: 'Issue resolved by resetting ONT. Customer satisfied.',
    status: 'completed',
    createdAt: getDateString(10),
    closedAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
    // Mock closure image (base64 placeholder). Replace with real backend image URL later.
    closureImage: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mP8z8BQDwAEhQGAhKmMIQAAAABJRU5ErkJggg==',
  },
  {
    id: 8,
    organizationId: MOCK_ORGANIZATION_ID,
    customerId: 8,
    customerName: 'Kavita Nair',
    mobile: '9876543217',
    connectionType: 'Cable',
    customerDescription: 'Need to upgrade plan. Current plan not sufficient for work from home.',
    internalDescription: 'Contacted customer. Upgrading to 200 Mbps plan.',
    status: 'active',
    createdAt: getDateString(1),
  },
  {
    id: 9,
    organizationId: MOCK_ORGANIZATION_ID,
    customerId: 9,
    customerName: 'Mohit Agarwal',
    mobile: '9876543218',
    connectionType: 'Internet 1',
    customerDescription: 'Fiber cable cut due to construction work. Need repair.',
    internalDescription: 'Emergency repair team dispatched. ETA 4 hours.',
    status: 'active',
    createdAt: getDateString(0),
  },
  {
    id: 10,
    organizationId: MOCK_ORGANIZATION_ID,
    customerId: 10,
    customerName: 'Divya Joshi',
    mobile: '9876543219',
    connectionType: 'Internet 3',
    customerDescription: 'Payment gateway issue. Unable to pay online bill.',
    internalDescription: 'Payment gateway working. Customer can try alternative payment method.',
    status: 'on-hold',
    createdAt: getDateString(4),
  },
  {
    id: 11,
    organizationId: MOCK_ORGANIZATION_ID,
    customerId: 11,
    customerName: 'Arjun Malhotra',
    mobile: '9876543220',
    connectionType: 'Internet 2',
    customerDescription: 'High ping in online games. Connection unstable during gaming.',
    internalDescription: 'Checking latency. May need QoS configuration for gaming.',
    status: 'active',
    createdAt: getDateString(2),
  },
  {
    id: 12,
    organizationId: MOCK_ORGANIZATION_ID,
    customerId: 12,
    customerName: 'Pooja Desai',
    mobile: '9876543221',
    connectionType: 'Cable',
    customerDescription: 'Router configuration issue resolved. Working fine now.',
    internalDescription: 'Fixed router settings. Connection stable now.',
    status: 'completed',
    createdAt: getDateString(8),
    closedAt: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 13,
    organizationId: MOCK_ORGANIZATION_ID,
    customerId: 13,
    customerName: 'Suresh Iyer',
    mobile: '9876543222',
    connectionType: 'Internet 1',
    customerDescription: 'Service reconnection request. Want to resume connection.',
    internalDescription: 'Processing reconnection. Will activate within 24 hours.',
    status: 'active',
    createdAt: getDateString(1),
  },
  {
    id: 14,
    organizationId: MOCK_ORGANIZATION_ID,
    customerId: 14,
    customerName: 'Meera Krishnan',
    mobile: '9876543223',
    connectionType: 'Internet 3',
    customerDescription: 'Business connection needs dedicated IP address. Please provide.',
    internalDescription: 'Dedicated IP allocation in progress. Requires network configuration.',
    status: 'on-hold',
    createdAt: getDateString(6),
  },
  {
    id: 15,
    organizationId: MOCK_ORGANIZATION_ID,
    customerId: 15,
    customerName: 'Nikhil Kapoor',
    mobile: '9876543224',
    connectionType: 'Cable',
    customerDescription: 'Streaming quality poor. Buffering issues on Netflix and YouTube.',
    internalDescription: 'Investigating bandwidth allocation. May need to optimize streaming traffic.',
    status: 'active',
    createdAt: getDateString(0),
  },
  {
    id: 16,
    organizationId: MOCK_ORGANIZATION_ID,
    customerId: 16,
    customerName: 'Riya Banerjee',
    mobile: '9876543225',
    connectionType: 'Internet 2',
    customerDescription: 'Connection restored. Issue was from ISP side, now fixed.',
    internalDescription: 'Network maintenance completed. All services restored.',
    status: 'completed',
    createdAt: getDateString(12),
    closedAt: new Date(Date.now() - 12 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 17,
    organizationId: MOCK_ORGANIZATION_ID,
    customerId: 17,
    customerName: 'Karan Thakur',
    mobile: '9876543226',
    connectionType: 'Internet 1',
    customerDescription: 'Need to relocate connection to new address. Please arrange.',
    internalDescription: 'Relocation request received. Survey scheduled for next week.',
    status: 'active',
    createdAt: getDateString(2),
  },
  {
    id: 18,
    organizationId: MOCK_ORGANIZATION_ID,
    customerId: 18,
    customerName: 'Shreya Menon',
    mobile: '9876543227',
    connectionType: 'Internet 3',
    customerDescription: 'Technical support ticket resolved. Customer satisfied.',
    internalDescription: 'All issues resolved. Customer feedback positive.',
    status: 'completed',
    createdAt: getDateString(15),
    closedAt: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000).toISOString(),
  },
];
